/*
 * Copyright (c) 2009-2015 Samsung Electronics Co., Ltd All Rights Reserved
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */


#ifndef _CALLUI_VIEW_LAYOUT_WVGA_H_
#define _CALLUI_VIEW_LAYOUT_WVGA_H_

#define COLOR_DEFAULT 0 0 0 255
#define COLOR_BG_ALPHA 0 0 0 0
#define COLOR_BG_FOR_HELD_CALL_DIM 0 0 0 150

#define VC_FONT_BOLD "Tizen:style=Bold"
#define VC_FONT_MEDIUM "Tizen:style=Medium"
#define VC_FONT_ROMAN "Tizen:style=Roman"
#define VC_FONT_LIGHT "Tizen:style=Light"
#define VC_FONT_REGULAR "Tizen:style=Regular"

#define VC_TEXT_CLASS_BOLD "tizen"
#define VC_TEXT_CLASS_MEDIUM "tizen"
#define VC_TEXT_CLASS_ROMAN "tizen"
#define VC_TEXT_CLASS_LIGHT "tizen"
#define VC_TEXT_CLASS_REGULAR "tizen"

/*
 * NBEAT-HD GUI Widget Dimensions
 * In Portrait mode
 */
#define MAIN_SCREEN_W 480
#define MAIN_SCREEN_H 800
#define MAIN_SCREEN_BIG_H 1280
#define MAIN_SCREEN_BIG_W 720
#define INDICATOR_HEIGHT 36

#define MAIN_LAYOUT_W MAIN_SCREEN_W
#define MAIN_LAYOUT_H MAIN_SCREEN_H

#define QP_WIN_W MAIN_SCREEN_W
#define QP_WIN_H 208

/* Need to be checked */
#define CALLER_INFO_NAME_DEFAULT_FONT_SIZE 12
#define CALLER_INFO_NAME_MIN_FONT_SIZE 12
#define CALLER_INFO_NAME_MAX_FONT_SIZE 15

#define NORMAL_HOLD_FONT_SIZE 36
#define DISABLED_HOLD_FONT_SIZE NORMAL_HOLD_FONT_SIZE
#define NORMAL_UNHOLD_FONT_SIZE NORMAL_HOLD_FONT_SIZE
#define DISABLED_UNHOLD_FONT_SIZE NORMAL_HOLD_FONT_SIZE
#define NORMAL_SWAP_FONT_SIZE NORMAL_HOLD_FONT_SIZE
#define DISABLED_SWAP_FONT_SIZE NORMAL_HOLD_FONT_SIZE
/***************************/

#define CALLER_INFO_L_PAD 0
#define CALLER_INFO_WIDTH MAIN_SCREEN_W
#define CALLER_INFO_T_PAD 0
#define CALLER_INFO_HEIGHT (398+INDICATOR_HEIGHT)

#define CALLER_INFO_MAIN_WIDTH 450

#define CALLER_INFO_STATUS_L_PAD 15
#define CALLER_INFO_STATUS_T_PAD (INDICATOR_HEIGHT+24)
#define CALLER_INFO_STATUS_WIDTH CALLER_INFO_MAIN_WIDTH
#define CALLER_INFO_STATUS_HEIGHT 30

#define CALL_STATUS_MAX_TEXT_WIDTH 290
#define TXT_TIMER_MAX_TEXT_WIDTH 100

#define VC_CALLER_ID_LAYOUT_L_PAD CALLER_INFO_STATUS_L_PAD
#define VC_CALLER_ID_LAYOUT_WIDTH CALLER_INFO_MAIN_WIDTH
#define VC_CALLER_ID_LAYOUT_T_PAD (CALLER_INFO_STATUS_T_PAD+CALLER_INFO_STATUS_HEIGHT+24)
#define VC_CALLER_ID_LAYOUT_HEIGHT 186
#define VC_CALLER_ID_WIDTH 186
#define VC_CALLER_ID_HEIGHT 186

#define CALLER_INFO_NAME_L_PAD CALLER_INFO_STATUS_L_PAD
#define CALLER_INFO_NAME_WIDTH CALLER_INFO_MAIN_WIDTH
#define CALLER_INFO_NAME_T_PAD (VC_CALLER_ID_LAYOUT_T_PAD+VC_CALLER_ID_LAYOUT_HEIGHT+10)
#define CALLER_INFO_NAME_HEIGHT 57
#define CALLER_INFO_EMERGENCY_HEIGHT 86

#define CALLER_INFO_NAME_1LINE_T_PAD (VC_CALLER_ID_LAYOUT_T_PAD+VC_CALLER_ID_LAYOUT_HEIGHT+9)
#define CALLER_INFO_NAME_1LINE_HEIGHT 100

#define CALLER_INFO_NUMBER_L_PAD CALLER_INFO_NAME_L_PAD
#define CALLER_INFO_NUMBER_WIDTH CALLER_INFO_MAIN_WIDTH
#define CALLER_INFO_NUMBER_T_PAD (CALLER_INFO_NAME_T_PAD+CALLER_INFO_NAME_HEIGHT+8)
#define CALLER_INFO_NUMBER_HEIGHT 36

#define CALLER_INFO_CARRIER_L_PAD CALLER_INFO_STATUS_L_PAD
#define CALLER_INFO_CARRIER_WIDTH 76
#define CALLER_INFO_CARRIER_T_PAD (INDICATOR_HEIGHT+66)
#define CALLER_INFO_CARRIER_HEIGHT 28


#define CALLER_INFO_MIN_WIDTH 50

#define ENDCALL_BTN_BG_WIDTH MAIN_SCREEN_W
#define ENDCALL_BTN_BG_HEIGHT 95
#define ENDCALL_BTN_BG_L_PAD 0
#define ENDCALL_BTN_BG_T_PAD MAIN_LAYOUT_H-ENDCALL_BTN_BG_HEIGHT

#define STYLE_ICN_T_PAD 21
#define STYLE_ICN_B 67
#define STYLE_TXT_T_PAD 79
#define STYLE_TXT_B 109
#define STYLE_TXT_L_PAD 10
#define STYLE_TXT_R 150
#define STYLE_TXT_WIDTH 140
#define STYLE_TXT_HEIGHT 30
#define STYLE_ONOFF_BAR_T_PAD 114
#define STYLE_ONOFF_BAR_B 120
#define STYLE_ONOFF_BAR_L_PAD 13
#define STYLE_ONOFF_BAR_R 147



#ifdef _VC_ANSWERING_MEMO
#define VC_ANSWERING_INFO_L_PAD 0
#define VC_ANSWERING_INFO_WIDTH MAIN_SCREEN_W
#define VC_ANSWERING_INFO_T_PAD 630
#define VC_ANSWERING_INFO_HEIGHT 50
#endif /* _VC_ANSWERING_MEMO */

#define MTLOCK_CALL_ICON_W	94
#define MTLOCK_CALL_ICON_H	94

#define MTLOCK_ACCEPT_OUTER_CIRCLE_BG_L_PAD (-102)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_BG_WIDTH 376
#define MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD (CALLER_INFO_HEIGHT-30)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_BG_HEIGHT 376

#define MTLOCK_ACCEPT_INNER_CIRCLE_L_PAD 32
#define MTLOCK_ACCEPT_INNER_CIRCLE_WIDTH 109
#define MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD (INDICATOR_HEIGHT+502)
#define MTLOCK_ACCEPT_INNER_CIRCLE_HEIGHT 109

#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD 32
#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_WIDTH 273
#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD
#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_HEIGHT 109

#define MTLOCK_ACCEPT_CIRCLE_ARROW_GAP 4

#define MTLOCK_ACCEPT_CIRCLE_ARROW2_L_PAD MTLOCK_ACCEPT_INNER_CIRCLE_L_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_WIDTH
#define MTLOCK_ACCEPT_CIRCLE_ARROW2_WIDTH 8
#define MTLOCK_ACCEPT_CIRCLE_ARROW2_T_PAD MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD+28
#define MTLOCK_ACCEPT_CIRCLE_ARROW2_HEIGHT 44

#define MTLOCK_ACCEPT_CIRCLE_ARROW1_L_PAD MTLOCK_ACCEPT_CIRCLE_ARROW2_L_PAD-MTLOCK_ACCEPT_CIRCLE_ARROW_GAP-MTLOCK_ACCEPT_CIRCLE_ARROW1_WIDTH
#define MTLOCK_ACCEPT_CIRCLE_ARROW1_WIDTH MTLOCK_ACCEPT_CIRCLE_ARROW2_WIDTH
#define MTLOCK_ACCEPT_CIRCLE_ARROW1_T_PAD MTLOCK_ACCEPT_CIRCLE_ARROW2_T_PAD
#define MTLOCK_ACCEPT_CIRCLE_ARROW1_HEIGHT MTLOCK_ACCEPT_CIRCLE_ARROW2_HEIGHT

#define MTLOCK_ACCEPT_ARROW1_L_PAD 160
#define MTLOCK_ACCEPT_ARROW1_WIDTH 12
#define MTLOCK_ACCEPT_ARROW1_T_PAD (MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD+33)
#define MTLOCK_ACCEPT_ARROW1_HEIGHT 19

#define MTLOCK_ACCEPT_ARROW2_L_PAD (MTLOCK_ACCEPT_ARROW1_L_PAD+MTLOCK_ACCEPT_ARROW1_WIDTH+17)
#define MTLOCK_ACCEPT_ARROW2_WIDTH MTLOCK_ACCEPT_ARROW1_WIDTH
#define MTLOCK_ACCEPT_ARROW2_T_PAD MTLOCK_ACCEPT_ARROW1_T_PAD
#define MTLOCK_ACCEPT_ARROW2_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define MTLOCK_ACCEPT_ARROW3_L_PAD (MTLOCK_ACCEPT_ARROW2_L_PAD+MTLOCK_ACCEPT_ARROW2_WIDTH+17)
#define MTLOCK_ACCEPT_ARROW3_WIDTH MTLOCK_ACCEPT_ARROW1_WIDTH
#define MTLOCK_ACCEPT_ARROW3_T_PAD MTLOCK_ACCEPT_ARROW1_T_PAD
#define MTLOCK_ACCEPT_ARROW3_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define MTLOCK_ACCEPT_ARROW4_L_PAD (MTLOCK_ACCEPT_ARROW3_L_PAD+MTLOCK_ACCEPT_ARROW3_WIDTH+17)
#define MTLOCK_ACCEPT_ARROW4_WIDTH MTLOCK_ACCEPT_ARROW1_WIDTH
#define MTLOCK_ACCEPT_ARROW4_T_PAD MTLOCK_ACCEPT_ARROW1_T_PAD
#define MTLOCK_ACCEPT_ARROW4_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define MTLOCK_REJECT_OUTER_CIRCLE_BG_L_PAD 206
#define MTLOCK_REJECT_OUTER_CIRCLE_BG_WIDTH MTLOCK_ACCEPT_OUTER_CIRCLE_BG_WIDTH
#define MTLOCK_REJECT_OUTER_CIRCLE_BG_T_PAD MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD
#define MTLOCK_REJECT_OUTER_CIRCLE_BG_HEIGHT MTLOCK_ACCEPT_OUTER_CIRCLE_BG_HEIGHT

#define MTLOCK_REJECT_INNER_CIRCLE_BG_L_PAD MAIN_SCREEN_W-MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD-MTLOCK_REJECT_INNER_CIRCLE_BG_WIDTH
#define MTLOCK_REJECT_INNER_CIRCLE_BG_WIDTH MTLOCK_ACCEPT_INNER_CIRCLE_BG_WIDTH
#define MTLOCK_REJECT_INNER_CIRCLE_BG_T_PAD MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD
#define MTLOCK_REJECT_INNER_CIRCLE_BG_HEIGHT MTLOCK_ACCEPT_INNER_CIRCLE_BG_HEIGHT

#define MTLOCK_REJECT_INNER_CIRCLE_L_PAD 339
#define MTLOCK_REJECT_INNER_CIRCLE_WIDTH MTLOCK_ACCEPT_INNER_CIRCLE_WIDTH
#define MTLOCK_REJECT_INNER_CIRCLE_T_PAD MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD
#define MTLOCK_REJECT_INNER_CIRCLE_HEIGHT MTLOCK_ACCEPT_INNER_CIRCLE_HEIGHT

#define MTLOCK_REJECT_CIRCLE_ARROW2_L_PAD MTLOCK_REJECT_INNER_CIRCLE_L_PAD+MTLOCK_ACCEPT_CIRCLE_ARROW_GAP
#define MTLOCK_REJECT_CIRCLE_ARROW2_WIDTH MTLOCK_ACCEPT_CIRCLE_ARROW1_WIDTH
#define MTLOCK_REJECT_CIRCLE_ARROW2_T_PAD MTLOCK_ACCEPT_CIRCLE_ARROW1_T_PAD
#define MTLOCK_REJECT_CIRCLE_ARROW2_HEIGHT MTLOCK_ACCEPT_CIRCLE_ARROW1_HEIGHT

#define MTLOCK_REJECT_CIRCLE_ARROW1_L_PAD MTLOCK_REJECT_CIRCLE_ARROW2_L_PAD-MTLOCK_ACCEPT_CIRCLE_ARROW_GAP-MTLOCK_REJECT_CIRCLE_ARROW1_WIDTH
#define MTLOCK_REJECT_CIRCLE_ARROW1_WIDTH MTLOCK_REJECT_CIRCLE_ARROW2_WIDTH
#define MTLOCK_REJECT_CIRCLE_ARROW1_T_PAD MTLOCK_REJECT_CIRCLE_ARROW2_T_PAD
#define MTLOCK_REJECT_CIRCLE_ARROW1_HEIGHT MTLOCK_REJECT_CIRCLE_ARROW2_HEIGHT

#define MTLOCK_REJECT_ARROW1_L_PAD (MTLOCK_REJECT_ARROW2_L_PAD-17-MTLOCK_REJECT_ARROW1_WIDTH)
#define MTLOCK_REJECT_ARROW1_WIDTH MTLOCK_ACCEPT_ARROW1_WIDTH
#define MTLOCK_REJECT_ARROW1_T_PAD (MTLOCK_REJECT_INNER_CIRCLE_T_PAD+68)
#define MTLOCK_REJECT_ARROW1_HEIGHT MTLOCK_ACCEPT_ARROW1_HEIGHT

#define MTLOCK_REJECT_ARROW2_L_PAD (MTLOCK_REJECT_ARROW3_L_PAD-17-MTLOCK_REJECT_ARROW2_WIDTH)
#define MTLOCK_REJECT_ARROW2_WIDTH MTLOCK_REJECT_ARROW1_WIDTH
#define MTLOCK_REJECT_ARROW2_T_PAD MTLOCK_REJECT_ARROW1_T_PAD
#define MTLOCK_REJECT_ARROW2_HEIGHT MTLOCK_REJECT_ARROW1_HEIGHT

#define MTLOCK_REJECT_ARROW3_L_PAD (MTLOCK_REJECT_ARROW4_L_PAD-17-MTLOCK_REJECT_ARROW3_WIDTH)
#define MTLOCK_REJECT_ARROW3_WIDTH MTLOCK_REJECT_ARROW1_WIDTH
#define MTLOCK_REJECT_ARROW3_T_PAD MTLOCK_REJECT_ARROW1_T_PAD
#define MTLOCK_REJECT_ARROW3_HEIGHT MTLOCK_REJECT_ARROW1_HEIGHT

#define MTLOCK_REJECT_ARROW4_WIDTH MTLOCK_REJECT_ARROW1_WIDTH
#define MTLOCK_REJECT_ARROW4_HEIGHT MTLOCK_REJECT_ARROW1_HEIGHT
#define MTLOCK_REJECT_ARROW4_L_PAD (MTLOCK_REJECT_INNER_CIRCLE_L_PAD-13-MTLOCK_REJECT_ARROW4_WIDTH)
#define MTLOCK_REJECT_ARROW4_T_PAD MTLOCK_REJECT_ARROW1_T_PAD

#define MTLOCK_REJECT_MSG_BG_L_PAD 0
#define MTLOCK_REJECT_MSG_BG_WIDTH MAIN_SCREEN_W
#define MTLOCK_REJECT_MSG_BG_HEIGHT 51
#define MTLOCK_REJECT_MSG_BG_T_PAD (MAIN_SCREEN_H-MTLOCK_REJECT_MSG_BG_HEIGHT)

#define MTLOCK_REJECT_MSG_ARW_L_PAD 225
#define MTLOCK_REJECT_MSG_ARW_WIDTH 29
#define MTLOCK_REJECT_MSG_ARW_HEIGHT 13
#define MTLOCK_REJECT_MSG_ARW_T_PAD (MTLOCK_REJECT_MSG_BG_T_PAD-MTLOCK_REJECT_MSG_ARW_HEIGHT)

#define MTLOCK_REJECT_MSG_DOWN_ARW_T_PAD MAIN_SCREEN_H

#define MTLOCK_REJECT_MSG_TEXT_L_PAD 0
#define MTLOCK_REJECT_MSG_TEXT_WIDTH MAIN_SCREEN_W
#define MTLOCK_REJECT_MSG_TEXT_T_PAD MTLOCK_REJECT_MSG_BG_T_PAD
#define MTLOCK_REJECT_MSG_TEXT_HEIGHT 51

#define MTLOCK_REJECT_MSG_TOP_VISIBLE_AREA_W (MTLOCK_REJECT_MSG_TEXT_HEIGHT+MTLOCK_REJECT_MSG_ARW_HEIGHT)

#define MTLOCK_ACTIVE_CALL_HEIGHT 360

#define ITEM_SIZE_H 120

#define REJ_MSG_LIST_W			MAIN_SCREEN_W
#define REJ_MSG_LIST_CREATE_MSG_BTN_H	150
#define REJ_MSG_LIST_CREATE_MSG_BTN_L_PAD	15
#define REJ_MSG_LIST_CREATE_MSG_BTN_R_PAD	REJ_MSG_LIST_CREATE_MSG_BTN_L_PAD
#define REJ_MSG_LIST_CREATE_MSG_BTN_T_PAD	17
#define REJ_MSG_LIST_CREATE_MSG_BTN_B_PAD	REJ_MSG_LIST_CREATE_MSG_BTN_T_PAD

#define MTLOCK_REJECT_MSG_LIST_L_PAD 0
#define MTLOCK_REJECT_MSG_LIST_WIDTH MAIN_SCREEN_W
#define MTLOCK_REJECT_MSG_LIST_T_PAD (MAIN_SCREEN_H+MTLOCK_REJECT_MSG_ARW_HEIGHT)
#define MTLOCK_REJECT_MSG_LIST_1ITEM_HEIGHT 86
#define MTLOCK_REJECT_MSG_LIST_1ITEM_NEW_HEIGHT 120
#define MTLOCK_REJECT_MSG_LIST_HEIGHT (MTLOCK_REJECT_MSG_LIST_1ITEM_NEW_HEIGHT*6)

/*Need to be fixed as Phone GUI guide*/
#define KEYPAD_ENTRY_TXT_L_PAD 15
#define KEYPAD_ENTRY_TXT_WIDTH 450
#define KEYPAD_ENTRY_TXT_T_PAD INDICATOR_HEIGHT
#define KEYPAD_ENTRY_TXT_HEIGHT (246)
/*****************************/

#define KEYPAD_AREA_HEIGHT (MAIN_SCREEN_H-ENDCALL_BTN_BG_HEIGHT)
#define KEYPAD_AREA_T_HIDE_PAD (MAIN_SCREEN_H-ENDCALL_BTN_BG_HEIGHT-KEYPAD_ENTRY_TXT_HEIGHT-INDICATOR_HEIGHT)

#define RIGHT_TXT_WIDTH 61

#define MULTI_LIST_HEIGHT MAIN_LAYOUT_H

#define SIX_BTN_LAYOUT_L_PAD 0
#define SIX_BTN_LAYOUT_WIDTH MAIN_SCREEN_W
#define SIX_BTN_LAYOUT_T_PAD (399+INDICATOR_HEIGHT)
#define SIX_BTN_LAYOUT_HEIGHT 258

#define BOTTOM_BTN_BG_L_PAD 0
#define BOTTOM_BTN_BG_WIDTH MAIN_SCREEN_W
#define BOTTOM_BTN_BG_T_PAD (CALLER_INFO_HEIGHT+SIX_BTN_LAYOUT_HEIGHT)
#define BOTTOM_BTN_BG_HEIGHT ENDCALL_BTN_BG_HEIGHT

#define BTN_LAYOUT_SINGLE_BTN_WIDTH 160
#define BTN_LAYOUT_SINGLE_BTN_HEIGHT 129
#define BTN_LAYOUT_GAP 0

#define BTN_LAYOUT_TOP_FIRST_BTN_L_PAD 0
#define BTN_LAYOUT_TOP_SECOND_BTN_L_PAD (BTN_LAYOUT_TOP_FIRST_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+BTN_LAYOUT_GAP)
#define BTN_LAYOUT_TOP_THIRD_BTN_L_PAD (BTN_LAYOUT_TOP_SECOND_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+BTN_LAYOUT_GAP)

#define BTN_LAYOUT_BOTTOM_FIRST_BTN_L_PAD 0
#define BTN_LAYOUT_BOTTOM_SECOND_BTN_L_PAD (BTN_LAYOUT_BOTTOM_FIRST_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+BTN_LAYOUT_GAP)
#define BTN_LAYOUT_BOTTOM_THIRD_BTN_L_PAD (BTN_LAYOUT_BOTTOM_SECOND_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+BTN_LAYOUT_GAP)

#define BTN_LAYOUT_TOP_BTNS_T_PAD BTN_LAYOUT_GAP
#define BTN_LAYOUT_BOTTOM_BTNS_T_PAD BTN_LAYOUT_TOP_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT+BTN_LAYOUT_GAP

/*two-button*/
#define ENDCALL_TWO_BTN_WIDTH MAIN_SCREEN_W
#define ENDCALL_TWO_BTN_HEIGHT 130
#define ENDCALL_TWO_BTN_L_PAD 0
#define ENDCALL_TWO_BTN_T_PAD (MAIN_LAYOUT_H-BOTTOM_BTN_BG_HEIGHT-ENDCALL_TWO_BTN_HEIGHT)
#define ENDCALL_TWO_BTN_R_PAD (ENDCALL_TWO_BTN_L_PAD+ENDCALL_TWO_BTN_WIDTH)
#define ENDCALL_TWO_BTN_B_PAD (ENDCALL_TWO_BTN_T_PAD+ENDCALL_TWO_BTN_HEIGHT)

#define ENDCALL_VOICE_BTN_L_PAD 15
#define ENDCALL_BTN_MID_PAD	10
#define ENDCALL_VIDEO_BTN_L_PAD (ENDCALL_VOICE_BTN_L_PAD+ENDCALL_BTN_WIDTH+ENDCALL_BTN_MID_PAD)
#define ENDCALL_VOICE_BTN_WIDTH 298
#define ENDCALL_BTN_WIDTH 142
#define ENDCALL_3_BTN_MSG_BTN_L_PAD (ENDCALL_VOICE_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH+ENDCALL_BTN_MID_PAD)

#define ENDCALL_VIEW_CONTACT_BTN_L_PAD 0
#define ENDCALL_VIEW_CONTACT_BTN_WIDTH MAIN_SCREEN_W
#define ENDCALL_VIEW_CONTACT_BTN_T_PAD 0
#define ENDCALL_VIEW_CONTACT_BTN_HEIGHT 130

#define ENDCALL_CREATE_CONTACT_BTN_L_PAD 0
#define ENDCALL_CREATE_CONTACT_BTN_WIDTH 240
#define ENDCALL_CREATE_CONTACT_BTN_T_PAD 0
#define ENDCALL_CREATE_CONTACT_BTN_HEIGHT 130

#define ENDCALL_UPDATE_CONTACT_BTN_L_PAD ENDCALL_CREATE_CONTACT_BTN_WIDTH

#define QP_TXT_AREA_L_PAD 15
#define QP_TXT_AREA_WIDTH 450
#define QP_TXT_AREA_T_PAD 14
#define QP_TXT_AREA_HEIGHT 36

#define QP_TITLE_WIDTH 290
#define QP_TITLE_HEIGHT 36

#define QP_TIME_WIDTH 160
#define QP_TIME_HEIGHT QP_TITLE_HEIGHT

#define QP_CALL_ICON_L_PAD 0
#define QP_CALL_ICON_WIDTH 119
#define QP_CALL_ICON_T_PAD 63
#define QP_CALL_ICON_HEIGHT 77

#define QP_CONTENT_ICON_T_PAD 13
#define QP_CONTENT_ICON_HEIGHT 50

#define QP_MUTE_BTN_L_PAD (QP_CALL_ICON_L_PAD+QP_CALL_ICON_WIDTH+1)
#define QP_MUTE_BTN_WIDTH QP_CALL_ICON_WIDTH
#define QP_MUTE_BTN_T_PAD QP_CALL_ICON_T_PAD
#define QP_MUTE_BTN_HEIGHT QP_CALL_ICON_HEIGHT

#define QP_SPEAKER_BTN_L_PAD (QP_MUTE_BTN_L_PAD+QP_MUTE_BTN_WIDTH+1)
#define QP_SPEAKER_BTN_WIDTH QP_CALL_ICON_WIDTH
#define QP_SPEAKER_BTN_T_PAD QP_CALL_ICON_T_PAD
#define QP_SPEAKER_BTN_HEIGHT QP_CALL_ICON_HEIGHT

#define QP_END_BTN_L_PAD (QP_SPEAKER_BTN_L_PAD+QP_SPEAKER_BTN_WIDTH+1)
#define QP_END_BTN_WIDTH 120
#define QP_END_BTN_T_PAD QP_CALL_ICON_T_PAD
#define QP_END_BTN_HEIGHT QP_CALL_ICON_HEIGHT

/*
 * QUICK-PANEL layout
 * In Portrait mode
 */
#define CALL_QUICKPANEL_TXT_AREA_L REL_QP_W(QP_TXT_AREA_L_PAD)
#define CALL_QUICKPANEL_TXT_AREA_R REL_QP_W(QP_TXT_AREA_L_PAD+QP_TXT_AREA_WIDTH)
#define CALL_QUICKPANEL_TXT_AREA_T REL_QP_H(QP_TXT_AREA_T_PAD)
#define CALL_QUICKPANEL_TXT_AREA_B REL_QP_H(QP_TXT_AREA_T_PAD+QP_TXT_AREA_HEIGHT)

#define CALL_QUICKPANEL_CALL_ICON_T REL_QP_H(QP_CALL_ICON_T_PAD)
#define CALL_QUICKPANEL_CALL_ICON_B REL_QP_H(QP_CALL_ICON_T_PAD+QP_CALL_ICON_HEIGHT)

#define CALL_QUICKPANEL_BTN_MUTE_T REL_QP_H(QP_MUTE_BTN_T_PAD)
#define CALL_QUICKPANEL_BTN_MUTE_B REL_QP_H(QP_MUTE_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define CALL_QUICKPANEL_BTN_SPEAKER_T REL_QP_H(QP_SPEAKER_BTN_T_PAD)
#define CALL_QUICKPANEL_BTN_SPEAKER_B REL_QP_H(QP_SPEAKER_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define CALL_QUICKPANEL_BTN_END_T REL_QP_H(QP_END_BTN_T_PAD)
#define CALL_QUICKPANEL_BTN_END_B REL_QP_H(QP_END_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define CALL_QUICKPANEL_BTN_ICON_T REL_QP_BTN_H(QP_CONTENT_ICON_T_PAD)
#define CALL_QUICKPANEL_BTN_ICON_B REL_QP_BTN_H(QP_CONTENT_ICON_T_PAD+QP_CONTENT_ICON_HEIGHT)
/*
 * End of QUICK-PANEL layout
 */

///////quickpanel////

/* Volume Popup Layout */
#define VOL_POPUP_PORTRAIT_H 102
#define VOL_POPUP_PORTRAIT_W 480

/*
 * End of NBEAT-HD GUI Widget Dimensions
 */


/*
 * Relative positions
 * In Portrait mode
 */
/* Relative X & Y positions of widgets w.r.t. Full Screen */
#define REL_W(x) ((x)/MAIN_SCREEN_W)
#define REL_H(y) ((y)/MAIN_LAYOUT_H)

/* Relative X & Y positions of widgets w.r.t. Quick-panel layout */
#define REL_QP_W(x) ((x)/QP_WIN_W)
#define REL_QP_H(y) ((y)/QP_WIN_H)

/* Relative X & Y positions of widgets w.r.t. Quick-panel button layout */
#define REL_QP_BTN_W(x) ((x)/QP_CALL_ICON_WIDTH)
#define REL_QP_BTN_H(y) ((y)/QP_CALL_ICON_HEIGHT)

/* Relative X & Y positions of buttons w.r.t. Six-Button layout - Portrait Mode */
#define REL_BTN_LY_W(x) ((x)/SIX_BTN_LAYOUT_WIDTH)
#define REL_BTN_LY_H(y) ((y)/SIX_BTN_LAYOUT_HEIGHT)

/* Relative X & Y positions of buttons w.r.t. Three-Button layout of ENDCALL*/
#define REL_THREE_BTN_LY_W(x) ((x)/THREE_BTN_LAYOUT_WIDTH)
#define REL_THREE_BTN_LY_H(y) ((y)/THREE_BTN_LAYOUT_HEIGHT)

/*Relative Y postions of elements w.r.t. Caller info layout*/
#define REL_CALLER_INFO_H(y) ((y)/CALLER_INFO_HEIGHT)

/*Relative Y postions of elements w.r.t. Multi list layout*/
#define REL_MULTI_LIST_H(y) ((y)/MULTI_LIST_HEIGHT)

#define REL_CONTACT_BTN_W(x) ((x)/MAIN_SCREEN_W)
#define REL_CONTACT_BTN_H(y) ((y)/ENDCALL_CREATE_CONTACT_BTN_HEIGHT)

#define REL_REJECT_MSG_W(x) ((x)/MAIN_SCREEN_W)
#define REL_REJECT_MSG_H(y) ((y)/MAIN_SCREEN_H)

#define REL_REJECT_MSG_SIZE_H(y) (1.0+(y)/MAIN_SCREEN_BIG_H)


/*
 * End of Relative positions
 */


/*
 * MO/Dialing view & MT/Incoming view
 * In Portrait mode
 */
#define BUTTON_REJECT_SIZE_H 78
#define BUTTON_OFFSET_B 22
#define BUTTON_OFFSET_T 20
#define IMAGE_CLOSE 18
#define IMAGE_OFFSET 12
#define VC_CALLER_ID_LAYOUT_L REL_W(147)
#define VC_CALLER_ID_LAYOUT_R REL_W(147+186)
#define VC_CALLER_ID_LAYOUT_T REL_CALLER_INFO_H(VC_CALLER_ID_LAYOUT_T_PAD)
#define VC_CALLER_ID_LAYOUT_B REL_CALLER_INFO_H(VC_CALLER_ID_LAYOUT_T_PAD+VC_CALLER_ID_LAYOUT_HEIGHT)

#define VC_CALLER_ID_EFFECT_L REL_W(140)
#define VC_CALLER_ID_EFFECT_R REL_W(140+200)
#define VC_CALLER_ID_EFFECT_T REL_CALLER_INFO_H(VC_CALLER_ID_LAYOUT_T_PAD-7)
#define VC_CALLER_ID_EFFECT_B REL_CALLER_INFO_H(VC_CALLER_ID_LAYOUT_T_PAD+VC_CALLER_ID_LAYOUT_HEIGHT+7)

#ifdef _VC_ANSWERING_MEMO
#define VC_ANSWERING_INFO_L REL_W(VC_ANSWERING_INFO_L_PAD)
#define VC_ANSWERING_INFO_R REL_W(VC_ANSWERING_INFO_L_PAD+VC_ANSWERING_INFO_WIDTH)
#define VC_ANSWERING_INFO_T REL_H(VC_ANSWERING_INFO_T_PAD)
#define VC_ANSWERING_INFO_B REL_H(VC_ANSWERING_INFO_T_PAD+VC_ANSWERING_INFO_HEIGHT)
#endif /* _VC_ANSWERING_MEMO */

/*
 * End of MO/Dialing view & MT/Incoming view
 */

/*
 * MT LOCK View - check
 * In Portrait mode
 */
#define MTLOCK_ACCEPT_CIRCLE_RECT_WIDTH	MAIN_SCREEN_W
#define MTLOCK_ACCEPT_CIRCLE_RECT_HEIGHT 313

#define MTLOCK_ACCEPT_INNER_CIRCLE_L REL_W(MTLOCK_ACCEPT_INNER_CIRCLE_L_PAD)
#define MTLOCK_ACCEPT_INNER_CIRCLE_R REL_W(MTLOCK_ACCEPT_INNER_CIRCLE_L_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_WIDTH)
#define MTLOCK_ACCEPT_INNER_CIRCLE_T REL_H(MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD)
#define MTLOCK_ACCEPT_INNER_CIRCLE_B REL_H(MTLOCK_ACCEPT_INNER_CIRCLE_T_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_HEIGHT)

#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_L REL_W(MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD)
#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_R REL_W(MTLOCK_ACCEPT_INNER_CIRCLE_BG_L_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_BG_WIDTH)
#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_T REL_H(MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD)
#define MTLOCK_ACCEPT_INNER_CIRCLE_BG_B REL_H(MTLOCK_ACCEPT_INNER_CIRCLE_BG_T_PAD+MTLOCK_ACCEPT_INNER_CIRCLE_BG_HEIGHT)

#define MTLOCK_ACCEPT_OUTER_CIRCLE_L REL_W(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_L_PAD)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_R REL_W(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_L_PAD+MTLOCK_ACCEPT_OUTER_CIRCLE_BG_WIDTH)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_T REL_H(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_B REL_H(MTLOCK_ACCEPT_OUTER_CIRCLE_BG_T_PAD+MTLOCK_ACCEPT_OUTER_CIRCLE_BG_HEIGHT)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_CLIP_RECT_T REL_H(CALLER_INFO_HEIGHT)
#define MTLOCK_ACCEPT_OUTER_CIRCLE_CLIP_RECT_B REL_H(MAIN_LAYOUT_H-MTLOCK_REJECT_MSG_BG_HEIGHT)


#define MTLOCK_ACCEPT_CIRCLE_ARROW1_L REL_W(MTLOCK_ACCEPT_CIRCLE_ARROW1_L_PAD)
#define MTLOCK_ACCEPT_CIRCLE_ARROW1_R REL_W(MTLOCK_ACCEPT_CIRCLE_ARROW1_L_PAD+MTLOCK_ACCEPT_CIRCLE_ARROW1_WIDTH)
#define MTLOCK_ACCEPT_CIRCLE_ARROW1_T REL_H(MTLOCK_ACCEPT_CIRCLE_ARROW1_T_PAD)
#define MTLOCK_ACCEPT_CIRCLE_ARROW1_B REL_H(MTLOCK_ACCEPT_CIRCLE_ARROW1_T_PAD+MTLOCK_ACCEPT_CIRCLE_ARROW1_HEIGHT)

#define MTLOCK_ACCEPT_CIRCLE_ARROW2_L REL_W(MTLOCK_ACCEPT_CIRCLE_ARROW2_L_PAD)
#define MTLOCK_ACCEPT_CIRCLE_ARROW2_R REL_W(MTLOCK_ACCEPT_CIRCLE_ARROW2_L_PAD+MTLOCK_ACCEPT_CIRCLE_ARROW2_WIDTH)
#define MTLOCK_ACCEPT_CIRCLE_ARROW2_T REL_H(MTLOCK_ACCEPT_CIRCLE_ARROW2_T_PAD)
#define MTLOCK_ACCEPT_CIRCLE_ARROW2_B REL_H(MTLOCK_ACCEPT_CIRCLE_ARROW2_T_PAD+MTLOCK_ACCEPT_CIRCLE_ARROW2_HEIGHT)



#define MTLOCK_ACCEPT_ARROW1_L REL_W(MTLOCK_ACCEPT_ARROW1_L_PAD)
#define MTLOCK_ACCEPT_ARROW1_R REL_W(MTLOCK_ACCEPT_ARROW1_L_PAD+MTLOCK_ACCEPT_ARROW1_WIDTH)
#define MTLOCK_ACCEPT_ARROW1_T REL_H(MTLOCK_ACCEPT_ARROW1_T_PAD)
#define MTLOCK_ACCEPT_ARROW1_B REL_H(MTLOCK_ACCEPT_ARROW1_T_PAD+MTLOCK_ACCEPT_ARROW1_HEIGHT)

#define MTLOCK_ACCEPT_ARROW2_L REL_W(MTLOCK_ACCEPT_ARROW2_L_PAD)
#define MTLOCK_ACCEPT_ARROW2_R REL_W(MTLOCK_ACCEPT_ARROW2_L_PAD+MTLOCK_ACCEPT_ARROW2_WIDTH)
#define MTLOCK_ACCEPT_ARROW2_T REL_H(MTLOCK_ACCEPT_ARROW2_T_PAD)
#define MTLOCK_ACCEPT_ARROW2_B REL_H(MTLOCK_ACCEPT_ARROW2_T_PAD+MTLOCK_ACCEPT_ARROW2_HEIGHT)

#define MTLOCK_ACCEPT_ARROW3_L REL_W(MTLOCK_ACCEPT_ARROW3_L_PAD)
#define MTLOCK_ACCEPT_ARROW3_R REL_W(MTLOCK_ACCEPT_ARROW3_L_PAD+MTLOCK_ACCEPT_ARROW3_WIDTH)
#define MTLOCK_ACCEPT_ARROW3_T REL_H(MTLOCK_ACCEPT_ARROW3_T_PAD)
#define MTLOCK_ACCEPT_ARROW3_B REL_H(MTLOCK_ACCEPT_ARROW3_T_PAD+MTLOCK_ACCEPT_ARROW3_HEIGHT)

#define MTLOCK_ACCEPT_ARROW4_L REL_W(MTLOCK_ACCEPT_ARROW4_L_PAD)
#define MTLOCK_ACCEPT_ARROW4_R REL_W(MTLOCK_ACCEPT_ARROW4_L_PAD+MTLOCK_ACCEPT_ARROW4_WIDTH)
#define MTLOCK_ACCEPT_ARROW4_T REL_H(MTLOCK_ACCEPT_ARROW4_T_PAD)
#define MTLOCK_ACCEPT_ARROW4_B REL_H(MTLOCK_ACCEPT_ARROW4_T_PAD+MTLOCK_ACCEPT_ARROW4_HEIGHT)

#define MTLOCK_REJECT_INNER_CIRCLE_L REL_W(MTLOCK_REJECT_INNER_CIRCLE_L_PAD)
#define MTLOCK_REJECT_INNER_CIRCLE_R REL_W(MTLOCK_REJECT_INNER_CIRCLE_L_PAD+MTLOCK_REJECT_INNER_CIRCLE_WIDTH)
#define MTLOCK_REJECT_INNER_CIRCLE_T REL_H(MTLOCK_REJECT_INNER_CIRCLE_T_PAD)
#define MTLOCK_REJECT_INNER_CIRCLE_B REL_H(MTLOCK_REJECT_INNER_CIRCLE_T_PAD+MTLOCK_REJECT_INNER_CIRCLE_HEIGHT)

#define MTLOCK_REJECT_INNER_CIRCLE_BG_L REL_W(MTLOCK_REJECT_INNER_CIRCLE_BG_L_PAD)
#define MTLOCK_REJECT_INNER_CIRCLE_BG_R REL_W(MTLOCK_REJECT_INNER_CIRCLE_BG_L_PAD+MTLOCK_REJECT_INNER_CIRCLE_BG_WIDTH)
#define MTLOCK_REJECT_INNER_CIRCLE_BG_T REL_H(MTLOCK_REJECT_INNER_CIRCLE_BG_T_PAD)
#define MTLOCK_REJECT_INNER_CIRCLE_BG_B REL_H(MTLOCK_REJECT_INNER_CIRCLE_BG_T_PAD+MTLOCK_REJECT_INNER_CIRCLE_BG_HEIGHT)

#define MTLOCK_REJECT_OUTER_CIRCLE_L REL_W(MTLOCK_REJECT_OUTER_CIRCLE_BG_L_PAD)
#define MTLOCK_REJECT_OUTER_CIRCLE_R REL_W(MTLOCK_REJECT_OUTER_CIRCLE_BG_L_PAD+MTLOCK_REJECT_OUTER_CIRCLE_BG_WIDTH)
#define MTLOCK_REJECT_OUTER_CIRCLE_T REL_H(MTLOCK_REJECT_OUTER_CIRCLE_BG_T_PAD)
#define MTLOCK_REJECT_OUTER_CIRCLE_B REL_H(MTLOCK_REJECT_OUTER_CIRCLE_BG_T_PAD+MTLOCK_REJECT_OUTER_CIRCLE_BG_HEIGHT)
#define MTLOCK_REJECT_OUTER_CIRCLE_CLIP_RECT_T REL_H(CALLER_INFO_HEIGHT)
#define MTLOCK_REJECT_OUTER_CIRCLE_CLIP_RECT_B REL_H(MAIN_LAYOUT_H-MTLOCK_REJECT_MSG_BG_HEIGHT)

#define MTLOCK_REJECT_CIRCLE_ARROW1_L REL_W(MTLOCK_REJECT_CIRCLE_ARROW1_L_PAD)
#define MTLOCK_REJECT_CIRCLE_ARROW1_R REL_W(MTLOCK_REJECT_CIRCLE_ARROW1_L_PAD+MTLOCK_REJECT_CIRCLE_ARROW1_WIDTH)
#define MTLOCK_REJECT_CIRCLE_ARROW1_T REL_H(MTLOCK_REJECT_CIRCLE_ARROW1_T_PAD)
#define MTLOCK_REJECT_CIRCLE_ARROW1_B REL_H(MTLOCK_REJECT_CIRCLE_ARROW1_T_PAD+MTLOCK_REJECT_CIRCLE_ARROW1_HEIGHT)

#define MTLOCK_REJECT_CIRCLE_ARROW2_L REL_W(MTLOCK_REJECT_CIRCLE_ARROW2_L_PAD)
#define MTLOCK_REJECT_CIRCLE_ARROW2_R REL_W(MTLOCK_REJECT_CIRCLE_ARROW2_L_PAD+MTLOCK_REJECT_CIRCLE_ARROW2_WIDTH)
#define MTLOCK_REJECT_CIRCLE_ARROW2_T REL_H(MTLOCK_REJECT_CIRCLE_ARROW2_T_PAD)
#define MTLOCK_REJECT_CIRCLE_ARROW2_B REL_H(MTLOCK_REJECT_CIRCLE_ARROW2_T_PAD+MTLOCK_REJECT_CIRCLE_ARROW2_HEIGHT)

#define MTLOCK_REJECT_ARROW1_L REL_W(MTLOCK_REJECT_ARROW1_L_PAD)
#define MTLOCK_REJECT_ARROW1_R REL_W(MTLOCK_REJECT_ARROW1_L_PAD+MTLOCK_REJECT_ARROW1_WIDTH)
#define MTLOCK_REJECT_ARROW1_T REL_H(MTLOCK_REJECT_ARROW1_T_PAD)
#define MTLOCK_REJECT_ARROW1_B REL_H(MTLOCK_REJECT_ARROW1_T_PAD+MTLOCK_REJECT_ARROW1_HEIGHT)

#define MTLOCK_REJECT_ARROW2_L REL_W(MTLOCK_REJECT_ARROW2_L_PAD)
#define MTLOCK_REJECT_ARROW2_R REL_W(MTLOCK_REJECT_ARROW2_L_PAD+MTLOCK_REJECT_ARROW2_WIDTH)
#define MTLOCK_REJECT_ARROW2_T REL_H(MTLOCK_REJECT_ARROW2_T_PAD)
#define MTLOCK_REJECT_ARROW2_B REL_H(MTLOCK_REJECT_ARROW2_T_PAD+MTLOCK_REJECT_ARROW2_HEIGHT)

#define MTLOCK_REJECT_ARROW3_L REL_W(MTLOCK_REJECT_ARROW3_L_PAD)
#define MTLOCK_REJECT_ARROW3_R REL_W(MTLOCK_REJECT_ARROW3_L_PAD+MTLOCK_REJECT_ARROW3_WIDTH)
#define MTLOCK_REJECT_ARROW3_T REL_H(MTLOCK_REJECT_ARROW3_T_PAD)
#define MTLOCK_REJECT_ARROW3_B REL_H(MTLOCK_REJECT_ARROW3_T_PAD+MTLOCK_REJECT_ARROW3_HEIGHT)

#define MTLOCK_REJECT_ARROW4_L REL_W(MTLOCK_REJECT_ARROW4_L_PAD)
#define MTLOCK_REJECT_ARROW4_R REL_W(MTLOCK_REJECT_ARROW4_L_PAD+MTLOCK_REJECT_ARROW4_WIDTH)
#define MTLOCK_REJECT_ARROW4_T REL_H(MTLOCK_REJECT_ARROW4_T_PAD)
#define MTLOCK_REJECT_ARROW4_B REL_H(MTLOCK_REJECT_ARROW4_T_PAD+MTLOCK_REJECT_ARROW4_HEIGHT)

#define MTLOCK_REJECT_MSG_BG_L REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_BG_L_PAD)
#define MTLOCK_REJECT_MSG_BG_R REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_BG_L_PAD+MTLOCK_REJECT_MSG_BG_WIDTH)
#define MTLOCK_REJECT_MSG_BG_T REL_REJECT_MSG_H(MTLOCK_REJECT_MSG_BG_T_PAD)
#define MTLOCK_REJECT_MSG_BG_B REL_REJECT_MSG_H(MTLOCK_REJECT_MSG_BG_T_PAD+MTLOCK_REJECT_MSG_BG_HEIGHT)

#define MTLOCK_REJECT_MSG_ARW_L REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_ARW_L_PAD)
#define MTLOCK_REJECT_MSG_ARW_R REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_ARW_L_PAD+MTLOCK_REJECT_MSG_ARW_WIDTH)
#define MTLOCK_REJECT_MSG_ARW_T REL_REJECT_MSG_H(MTLOCK_REJECT_MSG_ARW_T_PAD)
#define MTLOCK_REJECT_MSG_ARW_CLOSE_T 1.0
#define MTLOCK_REJECT_MSG_ARW_B REL_REJECT_MSG_H(MTLOCK_REJECT_MSG_ARW_T_PAD+MTLOCK_REJECT_MSG_ARW_HEIGHT)
#define MTLOCK_REJECT_MSG_ARW_CLOSE_B REL_REJECT_MSG_SIZE_H(IMAGE_CLOSE)

#define MTLOCK_REJECT_MSG_TEXT_L REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_TEXT_L_PAD)
#define MTLOCK_REJECT_MSG_TEXT_R REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_TEXT_L_PAD+MTLOCK_REJECT_MSG_TEXT_WIDTH)
#define MTLOCK_REJECT_MSG_TEXT_T REL_REJECT_MSG_H(MTLOCK_REJECT_MSG_TEXT_T_PAD)
#define MTLOCK_REJECT_MSG_TEXT_B REL_REJECT_MSG_H(MTLOCK_REJECT_MSG_TEXT_T_PAD+MTLOCK_REJECT_MSG_TEXT_HEIGHT)

#define MTLOCK_REJECT_MSG_LIST_L REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_LIST_L_PAD)
#define MTLOCK_REJECT_MSG_LIST_R REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_LIST_L_PAD+MTLOCK_REJECT_MSG_LIST_WIDTH)

#define MTLOCK_REJECT_MSG_DOWN_ARROW_T (1.0 - (IMAGE_OFFSET/MAIN_SCREEN_BIG_H))
#define MTLOCK_REJECT_MSG_DOWN_ARROW_B REL_REJECT_MSG_SIZE_H(IMAGE_CLOSE)

#define MTLOCK_REJECT_MSG_BTN_L REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_LIST_L_PAD)
#define MTLOCK_REJECT_MSG_BTN_R REL_REJECT_MSG_W(MTLOCK_REJECT_MSG_LIST_L_PAD+MTLOCK_REJECT_MSG_LIST_WIDTH)
#define MTLOCK_REJECT_MSG_BTN_T REL_REJECT_MSG_SIZE_H(IMAGE_CLOSE)
#define MTLOCK_REJECT_MSG_BTN_B REL_REJECT_MSG_SIZE_H(BUTTON_REJECT_SIZE_H+BUTTON_OFFSET_B+BUTTON_OFFSET_T+IMAGE_CLOSE)

#define REJECT_MSG (BUTTON_REJECT_SIZE_H+BUTTON_OFFSET_B+BUTTON_OFFSET_T+BUTTON_OFFSET_T)
#define MTLOCK_REJECT_MSG_LIST_NEW_T REL_REJECT_MSG_SIZE_H(REJECT_MSG)

#define MTLOCK_REJECT_MSG_LIST_6ITEMS_B REL_REJECT_MSG_SIZE_H((ITEM_SIZE_H*6)+REJECT_MSG)
#define MTLOCK_REJECT_MSG_LIST_5ITEMS_B REL_REJECT_MSG_SIZE_H((ITEM_SIZE_H*5)+REJECT_MSG)
#define MTLOCK_REJECT_MSG_LIST_4ITEMS_B REL_REJECT_MSG_SIZE_H((ITEM_SIZE_H*4)+REJECT_MSG)
#define MTLOCK_REJECT_MSG_LIST_3ITEMS_B REL_REJECT_MSG_SIZE_H((ITEM_SIZE_H*3)+REJECT_MSG)
#define MTLOCK_REJECT_MSG_LIST_2ITEMS_B REL_REJECT_MSG_SIZE_H((ITEM_SIZE_H*2)+REJECT_MSG)
#define MTLOCK_REJECT_MSG_LIST_1ITEM_B REL_REJECT_MSG_SIZE_H((ITEM_SIZE_H*1)+REJECT_MSG)
/*
 * End of MT LOCK View
 */

/*
 * KEYPAD View
 * In Portrait mode
 */
#define KEYPAD_AREA_T_HIDE REL_H(KEYPAD_AREA_T_HIDE_PAD)
#define KEYPAD_AREA_B_HIDE REL_H(KEYPAD_AREA_T_HIDE_PAD+KEYPAD_AREA_HEIGHT)

#define KEYPAD_ENTRY_TEXT_L REL_W(KEYPAD_ENTRY_TXT_L_PAD)
#define KEYPAD_ENTRY_TEXT_R REL_W(KEYPAD_ENTRY_TXT_L_PAD+KEYPAD_ENTRY_TXT_WIDTH)
#define KEYPAD_ENTRY_TEXT_T REL_H(KEYPAD_ENTRY_TXT_T_PAD)
#define KEYPAD_ENTRY_TEXT_B REL_H(KEYPAD_ENTRY_TXT_T_PAD+KEYPAD_ENTRY_TXT_HEIGHT)
/*
 * End of KEYPAD View
 */


/*
 * SIX BUTTON Layout
 * In Portrait mode
 */

#define	TOP_FIRST_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_TOP_FIRST_BTN_L_PAD)
#define	TOP_FIRST_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_SINGLE_BTN_WIDTH)
#define	TOP_FIRST_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_TOP_BTNS_T_PAD)
#define	TOP_FIRST_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_TOP_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define	TOP_SECOND_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_TOP_SECOND_BTN_L_PAD)
#define	TOP_SECOND_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_TOP_SECOND_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+1)
#define	TOP_SECOND_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_TOP_BTNS_T_PAD)
#define	TOP_SECOND_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_TOP_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define	TOP_THIRD_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_TOP_THIRD_BTN_L_PAD)
#define	TOP_THIRD_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_TOP_THIRD_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+2)
#define	TOP_THIRD_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_TOP_BTNS_T_PAD)
#define	TOP_THIRD_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_TOP_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define BOTTOM_FIRST_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_BOTTOM_FIRST_BTN_L_PAD)
#define BOTTOM_FIRST_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_BOTTOM_FIRST_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH)
#define BOTTOM_FIRST_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTNS_T_PAD)
#define BOTTOM_FIRST_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define BOTTOM_SECOND_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_BOTTOM_SECOND_BTN_L_PAD)
#define BOTTOM_SECOND_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_BOTTOM_SECOND_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+1)
#define BOTTOM_SECOND_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTNS_T_PAD)
#define BOTTOM_SECOND_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

#define BOTTOM_THIRD_BUTTON_L REL_BTN_LY_W(BTN_LAYOUT_BOTTOM_THIRD_BTN_L_PAD)
#define BOTTOM_THIRD_BUTTON_R REL_BTN_LY_W(BTN_LAYOUT_BOTTOM_THIRD_BTN_L_PAD+BTN_LAYOUT_SINGLE_BTN_WIDTH+2)
#define BOTTOM_THIRD_BUTTON_T REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTNS_T_PAD)
#define BOTTOM_THIRD_BUTTON_B REL_BTN_LY_H(BTN_LAYOUT_BOTTOM_BTNS_T_PAD+BTN_LAYOUT_SINGLE_BTN_HEIGHT)

/*
 * End of SIX Button Layout
 */

/*
 * General Button Layout
 * Portrait mode
 */
#define SIX_BTN_LAYOUT_L REL_W(SIX_BTN_LAYOUT_L_PAD)
#define SIX_BTN_LAYOUT_R REL_W(SIX_BTN_LAYOUT_L_PAD+SIX_BTN_LAYOUT_WIDTH)
#define SIX_BTN_LAYOUT_T REL_H(SIX_BTN_LAYOUT_T_PAD)
#define SIX_BTN_LAYOUT_B REL_H(SIX_BTN_LAYOUT_T_PAD+SIX_BTN_LAYOUT_HEIGHT)

/*
 * End of SIX Button Layout
 */

/*
 * Bottom Button layout
 */
#define BOTTOM_BTN_LAYOUT_L REL_W(BOTTOM_BTN_BG_L_PAD)
#define BOTTOM_BTN_LAYOUT_R REL_W(BOTTOM_BTN_BG_L_PAD+BOTTOM_BTN_BG_WIDTH)
#define BOTTOM_BTN_LAYOUT_T REL_H(BOTTOM_BTN_BG_T_PAD)
#define BOTTOM_BTN_LAYOUT_B REL_H(BOTTOM_BTN_BG_T_PAD+BOTTOM_BTN_BG_HEIGHT)
/*
 * End of Bottom Button layout
 */

/*
 * END CALL View
 * In Portrait mode
 */
#define ENDSINGLECALL_BTN_BG_L REL_W(ENDCALL_TWO_BTN_L_PAD)
#define ENDSINGLECALL_BTN_BG_R REL_W(ENDCALL_TWO_BTN_L_PAD+ENDCALL_TWO_BTN_WIDTH)
#define ENDSINGLECALL_BTN_BG_T REL_H(ENDCALL_TWO_BTN_T_PAD)
#define ENDSINGLECALL_BTN_BG_B REL_H(ENDCALL_TWO_BTN_T_PAD+ENDCALL_TWO_BTN_HEIGHT)

#define ENDSINGLECALL_VIEW_CONTACT_BTN_L REL_CONTACT_BTN_W(ENDCALL_VIEW_CONTACT_BTN_L_PAD)
#define ENDSINGLECALL_VIEW_CONTACT_BTN_R REL_CONTACT_BTN_W(ENDCALL_VIEW_CONTACT_BTN_L_PAD+ENDCALL_VIEW_CONTACT_BTN_WIDTH)
#define ENDSINGLECALL_VIEW_CONTACT_BTN_T REL_CONTACT_BTN_H(ENDCALL_VIEW_CONTACT_BTN_T_PAD)
#define ENDSINGLECALL_VIEW_CONTACT_BTN_B REL_CONTACT_BTN_H(ENDCALL_VIEW_CONTACT_BTN_T_PAD+ENDCALL_VIEW_CONTACT_BTN_HEIGHT)

#define ENDSINGLECALL_CREATE_CONTACT_BTN_L REL_CONTACT_BTN_W(ENDCALL_CREATE_CONTACT_BTN_L_PAD)
#define ENDSINGLECALL_CREATE_CONTACT_BTN_R REL_CONTACT_BTN_W(ENDCALL_CREATE_CONTACT_BTN_L_PAD+ENDCALL_CREATE_CONTACT_BTN_WIDTH)
#define ENDSINGLECALL_CREATE_CONTACT_BTN_T REL_CONTACT_BTN_H(ENDCALL_CREATE_CONTACT_BTN_T_PAD)
#define ENDSINGLECALL_CREATE_CONTACT_BTN_B REL_CONTACT_BTN_H(ENDCALL_CREATE_CONTACT_BTN_T_PAD+ENDCALL_CREATE_CONTACT_BTN_HEIGHT)

#define ENDSINGLECALL_UPDATE_CONTACT_BTN_L REL_CONTACT_BTN_W(ENDCALL_UPDATE_CONTACT_BTN_L_PAD)
#define ENDSINGLECALL_UPDATE_CONTACT_BTN_R REL_CONTACT_BTN_W(ENDCALL_UPDATE_CONTACT_BTN_L_PAD+ENDCALL_CREATE_CONTACT_BTN_WIDTH)
#define ENDSINGLECALL_UPDATE_CONTACT_BTN_T REL_CONTACT_BTN_H(ENDCALL_CREATE_CONTACT_BTN_T_PAD)
#define ENDSINGLECALL_UPDATE_CONTACT_BTN_B REL_CONTACT_BTN_H(ENDCALL_CREATE_CONTACT_BTN_T_PAD+ENDCALL_CREATE_CONTACT_BTN_HEIGHT)

#define ENDSINGLECALL_VIDEOCALL_BTN_BG_L REL_W(ENDCALL_VIDEO_BTN_L_PAD)
#define ENDSINGLECALL_VIDEOCALL_BTN_BG_R REL_W(ENDCALL_VIDEO_BTN_L_PAD+ENDCALL_BTN_WIDTH)

#define ENDSINGLECALL_CALL_BTN_BG_L REL_W(ENDCALL_VOICE_BTN_L_PAD)
#define ENDSINGLECALL_CALL_BTN_BG_R REL_W(ENDCALL_VOICE_BTN_L_PAD+ENDCALL_VOICE_BTN_WIDTH)

#define ENDSINGLECALL_MSG_BTN_BG_L REL_W(ENDCALL_3_BTN_MSG_BTN_L_PAD)
#define ENDSINGLECALL_MSG_BTN_BG_R REL_W(ENDCALL_3_BTN_MSG_BTN_L_PAD+ENDCALL_BTN_WIDTH)
/*
 * End of END CALL View
 */

/*
 * QUICK-PANEL layout
 * In Portrait mode
 */
#define CALL_QUICKPANEL_TXT_AREA_L REL_QP_W(QP_TXT_AREA_L_PAD)
#define CALL_QUICKPANEL_TXT_AREA_R REL_QP_W(QP_TXT_AREA_L_PAD+QP_TXT_AREA_WIDTH)
#define CALL_QUICKPANEL_TXT_AREA_T REL_QP_H(QP_TXT_AREA_T_PAD)
#define CALL_QUICKPANEL_TXT_AREA_B REL_QP_H(QP_TXT_AREA_T_PAD+QP_TXT_AREA_HEIGHT)

#define CALL_QUICKPANEL_CALL_ICON_L REL_QP_W(QP_CALL_ICON_L_PAD)
#define CALL_QUICKPANEL_CALL_ICON_R REL_QP_W(QP_CALL_ICON_L_PAD+QP_CALL_ICON_WIDTH)
#define CALL_QUICKPANEL_CALL_ICON_T REL_QP_H(QP_CALL_ICON_T_PAD)
#define CALL_QUICKPANEL_CALL_ICON_B REL_QP_H(QP_CALL_ICON_T_PAD+QP_CALL_ICON_HEIGHT)

#define CALL_QUICKPANEL_BTN_MUTE_L REL_QP_W(QP_MUTE_BTN_L_PAD)
#define CALL_QUICKPANEL_BTN_MUTE_R REL_QP_W(QP_MUTE_BTN_L_PAD+QP_MUTE_BTN_WIDTH)
#define CALL_QUICKPANEL_BTN_MUTE_T REL_QP_H(QP_MUTE_BTN_T_PAD)
#define CALL_QUICKPANEL_BTN_MUTE_B REL_QP_H(QP_MUTE_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define CALL_QUICKPANEL_BTN_SPEAKER_L REL_QP_W(QP_SPEAKER_BTN_L_PAD)
#define CALL_QUICKPANEL_BTN_SPEAKER_R REL_QP_W(QP_SPEAKER_BTN_L_PAD+QP_SPEAKER_BTN_WIDTH)
#define CALL_QUICKPANEL_BTN_SPEAKER_T REL_QP_H(QP_SPEAKER_BTN_T_PAD)
#define CALL_QUICKPANEL_BTN_SPEAKER_B REL_QP_H(QP_SPEAKER_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define CALL_QUICKPANEL_BTN_END_L REL_QP_W(QP_END_BTN_L_PAD)
#define CALL_QUICKPANEL_BTN_END_R REL_QP_W(QP_END_BTN_L_PAD+QP_END_BTN_WIDTH)
#define CALL_QUICKPANEL_BTN_END_T REL_QP_H(QP_END_BTN_T_PAD)
#define CALL_QUICKPANEL_BTN_END_B REL_QP_H(QP_END_BTN_T_PAD+QP_END_BTN_HEIGHT)

#define CALL_QUICKPANEL_BTN_ICON_T REL_QP_BTN_H(QP_CONTENT_ICON_T_PAD)
#define CALL_QUICKPANEL_BTN_ICON_B REL_QP_BTN_H(QP_CONTENT_ICON_T_PAD+QP_CONTENT_ICON_HEIGHT)
/*
 * End of QUICK-PANEL layout
 */


#define LSCAPE_TITLE_HEIGHT 100
#define LSCAPE_QP_WIN_W 1252
#define LSCAPE_QP_WIN_H 180

#define LSCAPE_QP_TITLE_L_PAD 14
#define LSCAPE_QP_TITLE_WIDTH 1050
#define LSCAPE_QP_TITLE_T_PAD 16
#define LSCAPE_QP_TITLE_HEIGHT 36

#define LSCAPE_QP_SPEAKER_BTN_L_PAD 18
#define LSCAPE_QP_SPEAKER_BTN_WIDTH 118
#define LSCAPE_QP_SPEAKER_BTN_T_PAD 75
#define LSCAPE_QP_SPEAKER_BTN_HEIGHT 72

#define LSCAPE_QP_MUTE_BTN_L_PAD (LSCAPE_QP_SPEAKER_BTN_L_PAD+LSCAPE_QP_SPEAKER_BTN_WIDTH+27)
#define LSCAPE_QP_MUTE_BTN_WIDTH LSCAPE_QP_SPEAKER_BTN_WIDTH
#define LSCAPE_QP_MUTE_BTN_T_PAD LSCAPE_QP_SPEAKER_BTN_T_PAD
#define LSCAPE_QP_MUTE_BTN_HEIGHT LSCAPE_QP_SPEAKER_BTN_HEIGHT

#define LSCAPE_QP_END_BTN_L_PAD (LSCAPE_QP_MUTE_BTN_L_PAD+LSCAPE_QP_MUTE_BTN_WIDTH+27)
#define LSCAPE_QP_END_BTN_WIDTH 72
#define LSCAPE_QP_END_BTN_T_PAD LSCAPE_QP_SPEAKER_BTN_T_PAD
#define LSCAPE_QP_END_BTN_HEIGHT 72

#define LSCAPE_QP_TIME_L_PAD (LSCAPE_QP_END_BTN_L_PAD+LSCAPE_QP_END_BTN_WIDTH+18)
#define LSCAPE_QP_TIME_WIDTH 181
#define LSCAPE_QP_TIME_T_PAD 114
#define LSCAPE_QP_TIME_HEIGHT 36

#define LSCAPE_QP_CALL_ICON_L_PAD 1122
#define LSCAPE_QP_CALL_ICON_WIDTH 106
#define LSCAPE_QP_CALL_ICON_T_PAD 34
#define LSCAPE_QP_CALL_ICON_HEIGHT 106
/* Relative X & Y positions of widgets w.r.t. Quick-panel layout */
#define REL_LSCAPE_QP_W(x) ((x)/LSCAPE_QP_WIN_W)
#define REL_LSCAPE_QP_H(y) ((y)/LSCAPE_QP_WIN_H)
/*
 * QUICK-PANEL layout
 * In Portrait mode
 */
#define LSCAPE_QUICKPANEL_TITLE_L REL_LSCAPE_QP_W(LSCAPE_QP_TITLE_L_PAD)
#define LSCAPE_QUICKPANEL_TITLE_R REL_LSCAPE_QP_W(LSCAPE_QP_TITLE_L_PAD+LSCAPE_QP_TITLE_WIDTH)
#define LSCAPE_QUICKPANEL_TITLE_T REL_LSCAPE_QP_H(LSCAPE_QP_TITLE_T_PAD)
#define LSCAPE_QUICKPANEL_TITLE_B REL_LSCAPE_QP_H(LSCAPE_QP_TITLE_T_PAD+LSCAPE_QP_TITLE_HEIGHT)

#define LSCAPE_QUICKPANEL_BTN_SPEAKER_L REL_LSCAPE_QP_W(LSCAPE_QP_SPEAKER_BTN_L_PAD)
#define LSCAPE_QUICKPANEL_BTN_SPEAKER_R REL_LSCAPE_QP_W(LSCAPE_QP_SPEAKER_BTN_L_PAD+LSCAPE_QP_SPEAKER_BTN_WIDTH)
#define LSCAPE_QUICKPANEL_BTN_SPEAKER_T REL_LSCAPE_QP_H(LSCAPE_QP_SPEAKER_BTN_T_PAD)
#define LSCAPE_QUICKPANEL_BTN_SPEAKER_B REL_LSCAPE_QP_H(LSCAPE_QP_SPEAKER_BTN_T_PAD+LSCAPE_QP_SPEAKER_BTN_HEIGHT)

#define LSCAPE_QUICKPANEL_BTN_MUTE_L REL_LSCAPE_QP_W(LSCAPE_QP_MUTE_BTN_L_PAD)
#define LSCAPE_QUICKPANEL_BTN_MUTE_R REL_LSCAPE_QP_W(LSCAPE_QP_MUTE_BTN_L_PAD+LSCAPE_QP_MUTE_BTN_WIDTH)
#define LSCAPE_QUICKPANEL_BTN_MUTE_T REL_LSCAPE_QP_H(LSCAPE_QP_MUTE_BTN_T_PAD)
#define LSCAPE_QUICKPANEL_BTN_MUTE_B REL_LSCAPE_QP_H(LSCAPE_QP_MUTE_BTN_T_PAD+LSCAPE_QP_MUTE_BTN_HEIGHT)

#define LSCAPE_QUICKPANEL_BTN_END_L REL_LSCAPE_QP_W(LSCAPE_QP_END_BTN_L_PAD)
#define LSCAPE_QUICKPANEL_BTN_END_R REL_LSCAPE_QP_W(LSCAPE_QP_END_BTN_L_PAD+LSCAPE_QP_END_BTN_WIDTH)
#define LSCAPE_QUICKPANEL_BTN_END_T REL_LSCAPE_QP_H(LSCAPE_QP_END_BTN_T_PAD)
#define LSCAPE_QUICKPANEL_BTN_END_B REL_LSCAPE_QP_H(LSCAPE_QP_END_BTN_T_PAD+LSCAPE_QP_END_BTN_HEIGHT)

#define LSCAPE_QUICKPANEL_TIME_L REL_LSCAPE_QP_W(LSCAPE_QP_TIME_L_PAD)
#define LSCAPE_QUICKPANEL_TIME_R REL_LSCAPE_QP_W(LSCAPE_QP_TIME_L_PAD+LSCAPE_QP_TIME_WIDTH)
#define LSCAPE_QUICKPANEL_TIME_T REL_LSCAPE_QP_H(LSCAPE_QP_TIME_T_PAD)
#define LSCAPE_QUICKPANEL_TIME_B REL_LSCAPE_QP_H(LSCAPE_QP_TIME_T_PAD+LSCAPE_QP_TIME_HEIGHT)

#define LSCAPE_QUICKPANEL_CALL_BG_ICON_L REL_LSCAPE_QP_W(LSCAPE_QP_CALL_BG_ICON_L_PAD)
#define LSCAPE_QUICKPANEL_CALL_BG_ICON_R REL_LSCAPE_QP_W(LSCAPE_QP_CALL_BG_ICON_L_PAD+LSCAPE_QP_CALL_BG_ICON_WIDTH)
#define LSCAPE_QUICKPANEL_CALL_BG_ICON_T REL_LSCAPE_QP_H(LSCAPE_QP_CALL_BG_ICON_T_PAD)
#define LSCAPE_QUICKPANEL_CALL_BG_ICON_B REL_LSCAPE_QP_H(LSCAPE_QP_CALL_BG_ICON_T_PAD+LSCAPE_QP_CALL_BG_ICON_HEIGHT)

#define LSCAPE_QUICKPANEL_CALL_ICON_L REL_LSCAPE_QP_W(LSCAPE_QP_CALL_ICON_L_PAD)
#define LSCAPE_QUICKPANEL_CALL_ICON_R REL_LSCAPE_QP_W(LSCAPE_QP_CALL_ICON_L_PAD+LSCAPE_QP_CALL_ICON_WIDTH)
#define LSCAPE_QUICKPANEL_CALL_ICON_T REL_LSCAPE_QP_H(LSCAPE_QP_CALL_ICON_T_PAD)
#define LSCAPE_QUICKPANEL_CALL_ICON_B REL_LSCAPE_QP_H(LSCAPE_QP_CALL_ICON_T_PAD+LSCAPE_QP_CALL_ICON_HEIGHT)

/*
 * Caller info layout
 * In Portrait mode
 */

#define CALLER_INFO_L REL_W(CALLER_INFO_L_PAD)
#define CALLER_INFO_R REL_W(CALLER_INFO_L_PAD+CALLER_INFO_WIDTH)
#define CALLER_INFO_T REL_H(CALLER_INFO_T_PAD)
#define CALLER_INFO_B REL_H(CALLER_INFO_T_PAD+CALLER_INFO_HEIGHT)

#define CALLER_INFO_NAME_L REL_W(CALLER_INFO_NAME_L_PAD)
#define CALLER_INFO_NAME_R REL_W(CALLER_INFO_NAME_L_PAD+CALLER_INFO_NAME_WIDTH)
#define CALLER_INFO_NAME_T REL_CALLER_INFO_H(CALLER_INFO_NAME_T_PAD)
#define CALLER_INFO_NAME_B REL_CALLER_INFO_H(CALLER_INFO_NAME_T_PAD+CALLER_INFO_NAME_HEIGHT)
#define CALLER_INFO_NAME_EMERGENCY_B REL_CALLER_INFO_H(CALLER_INFO_NAME_T_PAD+CALLER_INFO_EMERGENCY_HEIGHT)

#define CALLER_INFO_NAME_1LINE_T REL_CALLER_INFO_H(CALLER_INFO_NAME_1LINE_T_PAD)
#define CALLER_INFO_NAME_1LINE_B REL_CALLER_INFO_H(CALLER_INFO_NAME_1LINE_T_PAD+CALLER_INFO_NAME_1LINE_HEIGHT)

#define CALLER_INFO_NUMBER_L REL_W(CALLER_INFO_NUMBER_L_PAD)
#define CALLER_INFO_NUMBER_R REL_W(CALLER_INFO_NUMBER_L_PAD+CALLER_INFO_NUMBER_WIDTH)
#define CALLER_INFO_NUMBER_T REL_CALLER_INFO_H(CALLER_INFO_NUMBER_T_PAD)
#define CALLER_INFO_NUMBER_B REL_CALLER_INFO_H(CALLER_INFO_NUMBER_T_PAD+CALLER_INFO_NUMBER_HEIGHT)

#define CALLER_INFO_STATUS_L REL_W(CALLER_INFO_STATUS_L_PAD)
#define CALLER_INFO_STATUS_R REL_W(CALLER_INFO_STATUS_L_PAD+CALLER_INFO_STATUS_WIDTH)
#define CALLER_INFO_STATUS_T REL_CALLER_INFO_H(CALLER_INFO_STATUS_T_PAD)
#define CALLER_INFO_STATUS_B REL_CALLER_INFO_H(CALLER_INFO_STATUS_T_PAD+CALLER_INFO_STATUS_HEIGHT)

#define CALLER_INFO_CARRIER_L REL_W(CALLER_INFO_CARRIER_L_PAD)
#define CALLER_INFO_CARRIER_R REL_W(CALLER_INFO_CARRIER_L_PAD+CALLER_INFO_CARRIER_WIDTH)
#define CALLER_INFO_CARRIER_T REL_CALLER_INFO_H(CALLER_INFO_CARRIER_T_PAD)
#define CALLER_INFO_CARRIER_B REL_CALLER_INFO_H(CALLER_INFO_CARRIER_T_PAD+CALLER_INFO_CARRIER_HEIGHT)

#define EXTRA_LAYOUT_WIDTH MAIN_SCREEN_W
#define EXTRA_LAYOUT_HEIGHT 148

#define EXTRA_LAYOUT_L_PAD 0
#define EXTRA_LAYOUT_R_PAD (EXTRA_LAYOUT_L_PAD+EXTRA_LAYOUT_WIDTH)
#define EXTRA_LAYOUT_T_PAD (127)
#define EXTRA_LAYOUT_B_PAD (EXTRA_LAYOUT_T_PAD+148)

#define EXTRA2_LAYOUT_L_PAD 0
#define EXTRA2_LAYOUT_R_PAD (EXTRA2_LAYOUT_L_PAD+EXTRA_LAYOUT_WIDTH)
#define EXTRA2_LAYOUT_T_PAD (EXTRA_LAYOUT_B_PAD+1)
#define EXTRA2_LAYOUT_B_PAD (EXTRA2_LAYOUT_T_PAD+EXTRA_LAYOUT_HEIGHT)

#define EXTRA3_LAYOUT_L_PAD 0
#define EXTRA3_LAYOUT_R_PAD (EXTRA3_LAYOUT_L_PAD+EXTRA_LAYOUT_WIDTH)
#define EXTRA3_LAYOUT_T_PAD (EXTRA2_LAYOUT_B_PAD+1)
#define EXTRA3_LAYOUT_B_PAD (EXTRA3_LAYOUT_T_PAD+EXTRA_LAYOUT_HEIGHT)

#define EXTRA_LAYOUT_L REL_W(EXTRA_LAYOUT_L_PAD)
#define EXTRA_LAYOUT_R REL_W(EXTRA_LAYOUT_R_PAD)
#define EXTRA_LAYOUT_T REL_CALLER_INFO_H(EXTRA_LAYOUT_T_PAD)
#define EXTRA_LAYOUT_B REL_CALLER_INFO_H(EXTRA_LAYOUT_B_PAD)

#define EXTRA2_LAYOUT_L REL_W(EXTRA2_LAYOUT_L_PAD)
#define EXTRA2_LAYOUT_R REL_W(EXTRA2_LAYOUT_R_PAD)
#define EXTRA2_LAYOUT_T REL_CALLER_INFO_H(EXTRA2_LAYOUT_T_PAD)
#define EXTRA2_LAYOUT_B REL_CALLER_INFO_H(EXTRA2_LAYOUT_B_PAD)

#define EXTRA3_LAYOUT_L REL_W(EXTRA3_LAYOUT_L_PAD)
#define EXTRA3_LAYOUT_R REL_W(EXTRA3_LAYOUT_R_PAD)
#define EXTRA3_LAYOUT_T REL_CALLER_INFO_H(EXTRA3_LAYOUT_T_PAD)
#define EXTRA3_LAYOUT_B REL_CALLER_INFO_H(EXTRA3_LAYOUT_B_PAD)

#define REL_EXTRA_LAYOUT_H(y) ((y)/EXTRA_LAYOUT_HEIGHT)

#define EXTRA_LAYOUT_TEXT_WIDTH 450
#define EXTRA_LAYOUT_TEXT_HEIGHT 72
#define EXTRA_LAYOUT_TEXT_L_PAD 15
#define EXTRA_LAYOUT_TEXT_R_PAD (EXTRA_LAYOUT_TEXT_L_PAD+EXTRA_LAYOUT_TEXT_WIDTH)
#define EXTRA_LAYOUT_TEXT_T_PAD (12)
#define EXTRA_LAYOUT_TEXT_B_PAD (EXTRA_LAYOUT_TEXT_T_PAD+EXTRA_LAYOUT_TEXT_HEIGHT)

#define EXTRA_LAYOUT_TEXT_L REL_W(EXTRA_LAYOUT_TEXT_L_PAD)
#define EXTRA_LAYOUT_TEXT_R REL_W(EXTRA_LAYOUT_TEXT_R_PAD)
#define EXTRA_LAYOUT_TEXT_T REL_EXTRA_LAYOUT_H(EXTRA_LAYOUT_TEXT_T_PAD)
#define EXTRA_LAYOUT_TEXT_B REL_EXTRA_LAYOUT_H(EXTRA_LAYOUT_TEXT_B_PAD)

#define EXTRA_LAYOUT_RESUME_TEXT_WIDTH 365
#define EXTRA_LAYOUT_RESUME_TEXT_HEIGHT 96
#define EXTRA_LAYOUT_RESUME_TEXT_L_PAD 25
#define EXTRA_LAYOUT_RESUME_TEXT_R_PAD (EXTRA_LAYOUT_RESUME_TEXT_L_PAD+EXTRA_LAYOUT_RESUME_TEXT_WIDTH)
#define EXTRA_LAYOUT_RESUME_TEXT_T_PAD 0
#define EXTRA_LAYOUT_RESUME_TEXT_B_PAD (EXTRA_LAYOUT_RESUME_TEXT_T_PAD+EXTRA_LAYOUT_RESUME_TEXT_HEIGHT)

#define EXTRA_LAYOUT_RESUME_TEXT_L REL_W(EXTRA_LAYOUT_RESUME_TEXT_L_PAD)
#define EXTRA_LAYOUT_RESUME_TEXT_R REL_W(EXTRA_LAYOUT_RESUME_TEXT_R_PAD)
#define EXTRA_LAYOUT_RESUME_TEXT_T REL_EXTRA_LAYOUT_H(EXTRA_LAYOUT_RESUME_TEXT_T_PAD)
#define EXTRA_LAYOUT_RESUME_TEXT_B REL_EXTRA_LAYOUT_H(EXTRA_LAYOUT_RESUME_TEXT_B_PAD)

#define EXTRA_LAYOUT_RESUME_ICON_WIDTH 27
#define EXTRA_LAYOUT_RESUME_ICON_HEIGHT 27
#define EXTRA_LAYOUT_RESUME_ICON_L_PAD 339
#define EXTRA_LAYOUT_RESUME_ICON_R_PAD (EXTRA_LAYOUT_RESUME_ICON_L_PAD+EXTRA_LAYOUT_RESUME_ICON_WIDTH)
#define EXTRA_LAYOUT_RESUME_ICON_T_PAD INDICATOR_HEIGHT
#define EXTRA_LAYOUT_RESUME_ICON_B_PAD (EXTRA_LAYOUT_RESUME_ICON_T_PAD+72)

#define EXTRA_LAYOUT_RESUME_ICON_L REL_W(EXTRA_LAYOUT_RESUME_ICON_L_PAD)
#define EXTRA_LAYOUT_RESUME_ICON_R REL_W(EXTRA_LAYOUT_RESUME_ICON_R_PAD)
#define EXTRA_LAYOUT_RESUME_ICON_T REL_EXTRA_LAYOUT_H(EXTRA_LAYOUT_RESUME_ICON_T_PAD)
#define EXTRA_LAYOUT_RESUME_ICON_B REL_EXTRA_LAYOUT_H(EXTRA_LAYOUT_RESUME_ICON_B_PAD)

#define EXTRA_LAYOUT_EXTRA_VOL_ICON_L_PAD (EXTRA_LAYOUT_RESUME_ICON_L_PAD-34)
#define EXTRA_LAYOUT_EXTRA_VOL_ICON_R_PAD (EXTRA_LAYOUT_EXTRA_VOL_ICON_L_PAD+EXTRA_LAYOUT_RESUME_ICON_WIDTH)

#define EXTRA_LAYOUT_EXTRA_VOL_ICON_L REL_W(EXTRA_LAYOUT_EXTRA_VOL_ICON_L_PAD)
#define EXTRA_LAYOUT_EXTRA_VOL_ICON_R REL_W(EXTRA_LAYOUT_EXTRA_VOL_ICON_R_PAD)

#define HELD_CALL_CALLER_ID_WIDTH 74
#define HELD_CALL_CALLER_ID_HEIGHT EXTRA_LAYOUT_HEIGHT
#define HELD_CALL_CALLER_INFO_GAP 25
#define HELD_CALL_TEXT_WIDTH 186
#define HELD_CALL_TEXT_HEIGHT EXTRA_LAYOUT_HEIGHT
#define HELD_CALL_BTN_WIDTH 60
#define HELD_CALL_BTN_HEIGHT EXTRA_LAYOUT_HEIGHT
#define HELD_CALL_BTN_GAP 20

#define HELD_CALL_CALLER_ID_L	REL_W(15)
#define HELD_CALL_CALLER_ID_R	REL_W(15+HELD_CALL_CALLER_ID_WIDTH)
#define HELD_CALL_CALLER_ID_T	REL_EXTRA_LAYOUT_H(0)
#define HELD_CALL_CALLER_ID_B	REL_EXTRA_LAYOUT_H(HELD_CALL_CALLER_ID_T+HELD_CALL_CALLER_ID_HEIGHT)

#define HELD_CALL_TEXT_L_PAD	(20)
#define HELD_CALL_TEXT_T_PAD	0

#define HELD_CALL_TEXT_L	REL_W(HELD_CALL_TEXT_L_PAD)
#define HELD_CALL_TEXT_R	REL_W(HELD_CALL_TEXT_L_PAD+440)
#define HELD_CALL_TEXT_T	REL_EXTRA_LAYOUT_H(HELD_CALL_TEXT_T_PAD)
#define HELD_CALL_TEXT_B	REL_EXTRA_LAYOUT_H(HELD_CALL_TEXT_T_PAD+54)

#define HELD_CALL_BTN1_L_PAD	(0)
#define HELD_CALL_BTN1_T_PAD	50

#define HELD_CALL_BTN1_L	REL_W(HELD_CALL_BTN1_L_PAD)
#define HELD_CALL_BTN1_R	REL_W(HELD_CALL_BTN1_L_PAD+239)
#define HELD_CALL_BTN1_T	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN1_T_PAD)
#define HELD_CALL_BTN1_BG_B	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN1_T_PAD+98)
#define HELD_CALL_BTN1_B	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN1_T_PAD+60)
#define HELD_CALL_BTN1_TXT_T	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN1_T_PAD+60)
#define HELD_CALL_BTN1_TXT_B	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN1_T_PAD+60+25)

#define HELD_CALL_BTN2_L_PAD	240
#define HELD_CALL_BTN2_T_PAD	50

#define HELD_CALL_BTN2_L	REL_W(HELD_CALL_BTN2_L_PAD)
#define HELD_CALL_BTN2_R	REL_W(HELD_CALL_BTN2_L_PAD+240)
#define HELD_CALL_BTN2_T	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN2_T_PAD)
#define HELD_CALL_BTN2_BG_B	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN2_T_PAD+98)
#define HELD_CALL_BTN2_B	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN2_T_PAD+60)
#define HELD_CALL_BTN2_TXT_T	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN2_T_PAD+60)
#define HELD_CALL_BTN2_TXT_B	REL_EXTRA_LAYOUT_H(HELD_CALL_BTN2_T_PAD+60+25)

#define MANAGE_TEXT_WIDTH 280
#define MANAGE_TEXT_HEIGHT EXTRA_LAYOUT_HEIGHT

#define MANAGE_TEXT_L_PAD	(15+HELD_CALL_CALLER_ID_WIDTH+HELD_CALL_CALLER_INFO_GAP)
#define MANAGE_TEXT_T_PAD	0

#define MANAGE_TEXT_L	REL_W(MANAGE_TEXT_L_PAD)
#define MANAGE_TEXT_R	REL_W(MANAGE_TEXT_L_PAD+MANAGE_TEXT_WIDTH)
#define MANAGE_TEXT_T	REL_EXTRA_LAYOUT_H(MANAGE_TEXT_T_PAD)
#define MANAGE_TEXT_B	REL_EXTRA_LAYOUT_H(MANAGE_TEXT_T_PAD+MANAGE_TEXT_HEIGHT)

/*
 * End of Caller info layout
 */


/*
* Lock Screen Layout
*/

#define LOCK_SCREEN_LAYER_WIDTH MAIN_SCREEN_W
#define LOCK_SCREEN_LAYER_HEIGHT MAIN_SCREEN_H

#define LOCK_SCREEN_ICON_TOP_PAD 230
#define LOCK_SCREEN_ICON_HEIGHT 270

#define REL_LOCK_SCREEN_W(x) ((x)/LOCK_SCREEN_LAYER_WIDTH)
#define REL_LOCK_SCREEN_H(y) ((y)/LOCK_SCREEN_LAYER_HEIGHT)

#define LOCK_SCREEN_ICON_L REL_LOCK_SCREEN_W(0)
#define LOCK_SCREEN_ICON_R REL_LOCK_SCREEN_W(LOCK_SCREEN_LAYER_WIDTH)
#define LOCK_SCREEN_ICON_T REL_LOCK_SCREEN_H(LOCK_SCREEN_ICON_TOP_PAD)
#define LOCK_SCREEN_ICON_B REL_LOCK_SCREEN_H(LOCK_SCREEN_ICON_TOP_PAD+LOCK_SCREEN_ICON_HEIGHT)

#define LOCK_SCREEN_VERTICAL_GAP 20
#define LOCK_SCREEN_TEXT_LEFT_PADDING 15
#define LOCK_SCREEN_TEXT_RIGHT_PADDING 15
#define LOCK_SCREEN_TEXT_HEIGHT 144

#define EXTRA_VOL_OUTER_L_PAD (-204)
#define EXTRA_VOL_OUTER_WIDTH 544
#define EXTRA_VOL_OUTER_T_PAD 438
#define EXTRA_VOL_OUTER_HEIGHT 544

#define EXTRA_VOL_INNER_CIRCLE_L_PAD 23
#define EXTRA_VOL_INNER_CIRCLE_WIDTH 90
#define EXTRA_VOL_INNER_CIRCLE_T_PAD 665
#define EXTRA_VOL_INNER_CIRCLE_HEIGHT 90

#define END_CALL_OUTER_L_PAD 140
#define END_CALL_OUTER_WIDTH 544
#define END_CALL_OUTER_T_PAD EXTRA_VOL_OUTER_T_PAD
#define END_CALL_OUTER_HEIGHT 544

#define END_CALL_INNER_CIRCLE_L_PAD 367
#define END_CALL_INNER_CIRCLE_WIDTH 90
#define END_CALL_INNER_CIRCLE_T_PAD EXTRA_VOL_INNER_CIRCLE_T_PAD
#define END_CALL_INNER_CIRCLE_HEIGHT 90

#define LOCK_SCREEN_TEXT_L REL_LOCK_SCREEN_W(LOCK_SCREEN_TEXT_LEFT_PADDING)
#define LOCK_SCREEN_TEXT_R REL_LOCK_SCREEN_W(LOCK_SCREEN_LAYER_WIDTH-LOCK_SCREEN_TEXT_RIGHT_PADDING)
#define LOCK_SCREEN_TEXT_T REL_LOCK_SCREEN_H(LOCK_SCREEN_ICON_TOP_PAD+LOCK_SCREEN_ICON_HEIGHT+LOCK_SCREEN_VERTICAL_GAP)
#define LOCK_SCREEN_TEXT_B REL_LOCK_SCREEN_H(LOCK_SCREEN_ICON_TOP_PAD+LOCK_SCREEN_ICON_HEIGHT+LOCK_SCREEN_VERTICAL_GAP+LOCK_SCREEN_TEXT_HEIGHT)

#define LOCK_SCREEN_EXT_VOL_INNER_CIRCLE_L REL_W(EXTRA_VOL_INNER_CIRCLE_L_PAD)
#define LOCK_SCREEN_EXT_VOL_INNER_CIRCLE_R REL_W(EXTRA_VOL_INNER_CIRCLE_L_PAD+EXTRA_VOL_INNER_CIRCLE_WIDTH)
#define LOCK_SCREEN_EXT_VOL_INNER_CIRCLE_T REL_H(EXTRA_VOL_INNER_CIRCLE_T_PAD)
#define LOCK_SCREEN_EXT_VOL_INNER_CIRCLE_B REL_H(EXTRA_VOL_INNER_CIRCLE_T_PAD+EXTRA_VOL_INNER_CIRCLE_HEIGHT)

#define LOCK_SCREEN_EXT_VOL_OUTER_CIRCLE_L REL_W(EXTRA_VOL_OUTER_L_PAD)
#define LOCK_SCREEN_EXT_VOL_OUTER_CIRCLE_R REL_W(EXTRA_VOL_OUTER_L_PAD+EXTRA_VOL_OUTER_WIDTH)
#define LOCK_SCREEN_EXT_VOL_OUTER_CIRCLE_T REL_H(EXTRA_VOL_OUTER_T_PAD)
#define LOCK_SCREEN_EXT_VOL_OUTER_CIRCLE_B REL_H(EXTRA_VOL_OUTER_T_PAD+EXTRA_VOL_OUTER_HEIGHT)

#define LOCK_SCREEN_END_CALL_INNER_CIRCLE_L REL_W(END_CALL_INNER_CIRCLE_L_PAD)
#define LOCK_SCREEN_END_CALL_INNER_CIRCLE_R REL_W(END_CALL_INNER_CIRCLE_L_PAD+END_CALL_INNER_CIRCLE_WIDTH)
#define LOCK_SCREEN_END_CALL_INNER_CIRCLE_T REL_H(END_CALL_INNER_CIRCLE_T_PAD)
#define LOCK_SCREEN_END_CALL_INNER_CIRCLE_B REL_H(END_CALL_INNER_CIRCLE_T_PAD+END_CALL_INNER_CIRCLE_HEIGHT)

#define LOCK_SCREEN_END_CALL_OUTER_CIRCLE_L REL_W(END_CALL_OUTER_L_PAD)
#define LOCK_SCREEN_END_CALL_OUTER_CIRCLE_R REL_W(END_CALL_OUTER_L_PAD+END_CALL_OUTER_WIDTH)
#define LOCK_SCREEN_END_CALL_OUTER_CIRCLE_T REL_H(END_CALL_OUTER_T_PAD)
#define LOCK_SCREEN_END_CALL_OUTER_CIRCLE_B REL_H(END_CALL_OUTER_T_PAD+END_CALL_OUTER_HEIGHT)

/*
* End of Lock Screen Layout
*/

#endif /*_CALLUI_VIEW_LAYOUT_WVGA_H_*/
